### PR TITLE
Allow setting GH_TOKEN to avoid github IP rate limiting

### PR DESCRIPTION
**Pull request by flaub**

### CODE REVIEW

**Comment by sergeiivankov** [comment]
Hello! Thank you. Is it good idea force using token from GITHUB_TOKEN env variable? Or better we can add separate variable for this crate, PROTOC_PREBUILD_GITHUB_TOKEN, or variable, that accept usage GITHUB_TOKEN, for example PROTOC_PREBUILD_USE_GITHUB_TOKEN? I would like it to crate user can control token usage. What do you think? Sorry for long answer

**Comment by scx1332** [comment]
If you are using github actions is super useful to use GITHUB_TOKEN by default, separating it to another variable add additional parameters that need to be setup in github actions. I will vote for using GITHUB_TOKEN. We are encountering issue with rate limit also and need to work around it. 
Thank you for your work and looking for this change!

**Comment by flaub** [comment]
I can't think of a situation where using GITHUB_TOKEN for one crate or CI process but not for another would be something I'd run across.

**Comment by sergeiivankov** [comment]
Add required functional, see https://github.com/sergeiivankov/protoc-prebuilt/tree/4749bfad346dabc73d342633b1def6dc872459bb. Before publish on crates.io I plan add some more additions.
Thank you!

**Comment by sergeiivankov** [comment]
@flaub, @scx1332, new version with this functional available https://crates.io/crates/protoc-prebuilt!

**Pull request closed without merging**
